apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-storefront-ui-to-storefront-bff
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ .Release.Namespace }}/sa/storefront-ui
  selector:
    matchLabels:
      app: storefront-bff
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-backoffice-ui-to-backoffice-bff
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/{{ .Release.Namespace }}/sa/backoffice-ui
  selector:
    matchLabels:
      app: backoffice-bff
