{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
{{- range $serviceName, $serviceConfig := .Values }}
{{- if typeIs "map[string]interface {}" $serviceConfig }}
{{- if and (hasKey $serviceConfig "enabled") (eq $serviceConfig.enabled true) (hasKey $serviceConfig "service") (eq (default "" $serviceConfig.service.type) "NodePort") }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ $serviceName }}-nodeport
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $serviceName }}
  mtls:
    mode: STRICT
  portLevelMtls:
    {{ $serviceConfig.service.port }}:
      mode: PERMISSIVE
    {{- if $serviceConfig.isBackend }}
    8090:
      mode: DISABLE
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
