{{- if .Values.istio.enabled }}
---
# Retry policy for tax service.
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tax-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - tax
  http:
    - retries:
        attempts: 3
        perTryTimeout: 5s
        retryOn: "5xx,retriable-4xx,connect-failure,reset"
      timeout: 30s
      route:
        - destination:
            host: tax
            port:
              number: 80
---
# Retry policy for product service.
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - product
  http:
    - retries:
        attempts: 3
        perTryTimeout: 5s
        retryOn: "5xx,connect-failure,reset"
      timeout: 30s
      route:
        - destination:
            host: product
            port:
              number: 80
---
# Mock HEAD request to Elasticsearch to fix Spring Data ES client 9.x compatibility issue with ES 8.x
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elasticsearch-mock
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "elasticsearch-es-http.elasticsearch.svc.cluster.local"
    - "elasticsearch-es-http.elasticsearch"
  http:
    - match:
        - method:
            exact: HEAD
      directResponse:
        status: 200
      headers:
        response:
          set:
            X-Elastic-Product: "Elasticsearch"
    - route:
        - destination:
            host: elasticsearch-es-http.elasticsearch.svc.cluster.local
            port:
              number: 9200
{{- end }}