global:
  environment: dev

storefront-ui:
  enabled: true
  image:
    tag: main
storefront-bff:
  enabled: true
  image:
    tag: main
  env:
    SPRING_PROFILES_ACTIVE: "custom"
    SPRING_CLOUD_GATEWAY_ROUTES_2_URI: "http://storefront-ui:3000"
    SPRING_APPLICATION_JSON: >-
      {"spring":{"cloud":{"gateway":{"routes":[{"id":"api_servicename_local","uri":"http://api.yas.local","predicates":[{"name":"Path","args":{"pattern":"/api/servicename/**"}}],"filters":[{"name":"TokenRelay"},{"name":"StripPrefix","args":{"parts":1}}]},{"id":"api","uri":"http://api.yas.local","predicates":[{"name":"Path","args":{"pattern":"/api/**"}}],"filters":[{"name":"TokenRelay"},{"name":"StripPrefix","args":{"parts":1}}]},{"id":"nextjs","uri":"http://storefront-ui:3000","predicates":[{"name":"Path","args":{"pattern":"/**"}}]}]}}}}
backoffice-ui:
  enabled: true
  image:
    tag: main
backoffice-bff:
  enabled: true
  image:
    tag: main
  env:
    SPRING_APPLICATION_JSON: >-
      {"spring":{"cloud":{"gateway":{"routes":[{"id":"api_servicename_local","uri":"http://api.yas.local","predicates":[{"name":"Path","args":{"pattern":"/api/servicename/**"}}],"filters":[{"name":"RewritePath","args":{"regexp":"/api/(?<segment>.*)","replacement":"/$\\{segment}"}},{"name":"TokenRelay"}]},{"id":"api","uri":"http://api.yas.local","predicates":[{"name":"Path","args":{"pattern":"/api/**"}}],"filters":[{"name":"RewritePath","args":{"regexp":"/api/(?<segment>.*)","replacement":"/$\\{segment}"}},{"name":"TokenRelay"}]},{"id":"nextjs","uri":"http://backoffice-ui:3000","predicates":[{"name":"Path","args":{"pattern":"/**"}}]}]}}}}
product:
  enabled: true
  image:
    tag: main
media:
  enabled: true
  image:
    tag: main
customer:
  enabled: true
  image:
    tag: main
cart:
  enabled: true
  image:
    tag: main
order:
  enabled: true
  image:
    tag: main
inventory:
  enabled: true
  image:
    tag: main
tax:
  enabled: true
  image:
    tag: 2094d996
search:
  enabled: true
  image:
    tag: main
sampledata:
  enabled: true
  image:
    tag: main
swagger-ui:
  enabled: true
  image:
    tag: v5.17.14
