global:
  environment: dev
  configRevision: "jenkins-26"

istio:
  enabled: true  # Istio da cai tren GKE cluster yas-dev

storefront-ui:
  enabled: true
  image:
    tag: main
  env:
    API_BASE_PATH: "http://storefront-bff/api"
storefront-bff:
  enabled: true
  image:
    tag: main
  podAnnotations:
    rollout.yas.dev/payment-route: "098c4f6"
  env:
    SPRING_PROFILES_ACTIVE: "custom"
    SPRING_APPLICATION_JSON: >-
      {"spring":{"cloud":{"gateway":{"server":{"webflux":{"default-filters":["SaveSession"],"routes":[{"id":"product_api","uri":"http://product","predicates":["Path=/api/product/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"cart_api","uri":"http://cart","predicates":["Path=/api/cart/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"customer_api","uri":"http://customer","predicates":["Path=/api/customer/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"order_api","uri":"http://order","predicates":["Path=/api/order/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"tax_api","uri":"http://tax","predicates":["Path=/api/tax/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"inventory_api","uri":"http://inventory","predicates":["Path=/api/inventory/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"media_api","uri":"http://media","predicates":["Path=/api/media/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"location_api","uri":"http://location","predicates":["Path=/api/location/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"payment_api","uri":"http://payment","predicates":["Path=/api/payment/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"search_api","uri":"http://search","predicates":["Path=/api/search/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"sampledata_api","uri":"http://sampledata","predicates":["Path=/api/sampledata/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"nextjs","uri":"http://storefront-ui:3000","predicates":["Path=/**"]}]}}}}}}
backoffice-ui:
  enabled: true
  image:
    tag: main
  env:
    API_BASE_PATH: "http://backoffice-bff/api"
backoffice-bff:
  enabled: true
  image:
    tag: main
  env:
    SPRING_PROFILES_ACTIVE: "custom"
    SPRING_APPLICATION_JSON: >-
      {"spring":{"cloud":{"gateway":{"server":{"webflux":{"default-filters":["SaveSession"],"routes":[{"id":"product_api","uri":"http://product","predicates":["Path=/api/product/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"customer_api","uri":"http://customer","predicates":["Path=/api/customer/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"order_api","uri":"http://order","predicates":["Path=/api/order/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"tax_api","uri":"http://tax","predicates":["Path=/api/tax/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"inventory_api","uri":"http://inventory","predicates":["Path=/api/inventory/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"media_api","uri":"http://media","predicates":["Path=/api/media/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"location_api","uri":"http://location","predicates":["Path=/api/location/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"search_api","uri":"http://search","predicates":["Path=/api/search/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"nextjs","uri":"http://backoffice-ui:3000","predicates":["Path=/**"]}]}}}}}}
product:
  enabled: true
  image:
    tag: main
media:
  enabled: true
  image:
    tag: main
  podAnnotations:
    rollout.yas.dev/issuer-fix: "1"
  env:
    YAS_PUBLICURL: "/api/media"
    SERVER_SERVLET_CONTEXT_PATH: "/media"
customer:
  enabled: true
  image:
    tag: main
  podAnnotations:
    rollout.yas.dev/issuer-fix: "1"
location:
  enabled: true
  image:
    tag: main
  podAnnotations:
    rollout.yas.dev/issuer-fix: "1"
cart:
  enabled: true
  image:
    tag: main
  podAnnotations:
    rollout.yas.dev/issuer-fix: "1"
order:
  enabled: true
  image:
    tag: main
  podAnnotations:
    rollout.yas.dev/issuer-fix: "1"
payment:
  enabled: true
  image:
    tag: main
  podAnnotations:
    rollout.yas.dev/issuer-fix: "1"
  env:
    YAS_PUBLIC_URL: "http://storefront.yas.local/complete-payment"
inventory:
  enabled: true
  image:
    tag: main
tax:
  enabled: true
  image:
    tag: main
search:
  enabled: true
  image:
    tag: main
sampledata:
  enabled: true
  image:
    tag: main
  env:
    SPRING_DATASOURCE_PRODUCT_URL: "jdbc:postgresql://postgresql.postgres:5432/product"
    SPRING_DATASOURCE_MEDIA_URL: "jdbc:postgresql://postgresql.postgres:5432/media"
swagger-ui:
  enabled: true
  image:
    tag: v5.17.14
  podAnnotations:
    rollout.yas.dev/swagger-initializer: "yas-docs-v1"
  extraVolumes:
    - name: swagger-ui-initializer
      configMap:
        name: swagger-ui-initializer
  extraVolumeMounts:
    - name: swagger-ui-initializer
      mountPath: /usr/share/nginx/html/swagger-initializer.js
      subPath: swagger-initializer.js
