global:
  environment: staging

istio:
  enabled: true  # Istio đã cài trên GKE cluster

storefront-ui:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 3000
    nodePort: null

storefront-bff:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null
  env:
    SPRING_PROFILES_ACTIVE: "custom"
    SPRING_APPLICATION_JSON: '{"spring":{"cloud":{"gateway":{"server":{"webflux":{"default-filters":["SaveSession"],"routes":[{"id":"product_api","uri":"http://product","predicates":["Path=/api/product/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"cart_api","uri":"http://cart","predicates":["Path=/api/cart/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"customer_api","uri":"http://customer","predicates":["Path=/api/customer/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"order_api","uri":"http://order","predicates":["Path=/api/order/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"tax_api","uri":"http://tax","predicates":["Path=/api/tax/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"inventory_api","uri":"http://inventory","predicates":["Path=/api/inventory/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"media_api","uri":"http://media","predicates":["Path=/api/media/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"search_api","uri":"http://search","predicates":["Path=/api/search/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"sampledata_api","uri":"http://sampledata","predicates":["Path=/api/sampledata/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"nextjs","uri":"http://storefront-ui:3000","predicates":["Path=/**"]}]}}}}}}'

backoffice-ui:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 3000
    nodePort: null

backoffice-bff:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null
  env:
    SPRING_APPLICATION_JSON: '{"spring":{"cloud":{"gateway":{"server":{"webflux":{"default-filters":["SaveSession"],"routes":[{"id":"product_api","uri":"http://product","predicates":["Path=/api/product/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"customer_api","uri":"http://customer","predicates":["Path=/api/customer/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"order_api","uri":"http://order","predicates":["Path=/api/order/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"tax_api","uri":"http://tax","predicates":["Path=/api/tax/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"inventory_api","uri":"http://inventory","predicates":["Path=/api/inventory/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}","TokenRelay="]},{"id":"media_api","uri":"http://media","predicates":["Path=/api/media/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"search_api","uri":"http://search","predicates":["Path=/api/search/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"sampledata_api","uri":"http://sampledata","predicates":["Path=/api/sampledata/**"],"filters":["RewritePath=/api/(?<segment>.*), /${segment}"]},{"id":"nextjs","uri":"http://backoffice-ui:3000","predicates":["Path=/**"]}]}}}}}}'

product:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null

media:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null

customer:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null

cart:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null

order:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null

inventory:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null

tax:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null

search:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null

sampledata:
  enabled: true
  image:
    tag: main
  service:
    type: ClusterIP
    port: 80
    nodePort: null

swagger-ui:
  enabled: true
  image:
    tag: v5.17.14
  service:
    type: ClusterIP
    port: 8080
    nodePort: null

storefrontBffExtraConfig:
  spring:
    security:
      oauth2:
        client:
          provider:
            keycloak:
              issuer-uri: "http://identity/realms/Yas"
          registration:
            keycloak:
              client-id: storefront-bff
              client-secret: ${KEYCLOAK_STOREFRONT_BFF_CLIENT_SECRET}
              scope:
                - openid
                - profile
                - email
                - roles

backofficeBffExtraConfig:
  spring:
    security:
      oauth2:
        client:
          provider:
            keycloak:
              issuer-uri: "http://identity/realms/Yas"
          registration:
            keycloak:
              client-id: backoffice-bff
              client-secret: ${KEYCLOAK_BACKOFFICE_BFF_CLIENT_SECRET}
              scope:
                - openid
                - profile
                - email
                - roles