apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-frontends-to-backends
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.namespace }}/sa/storefront-bff
              - cluster.local/ns/{{ .Values.namespace }}/sa/backoffice-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-order-to-tax
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tax
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/{{ .Values.namespace }}/sa/order
              - cluster.local/ns/{{ .Values.namespace }}/sa/backoffice-bff
