apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging
  namespace: argocd
spec:
  project: yas
  source:
    repoURL: https://github.com/thu2005/gitops-yas.git
    targetRevision: staging
    path: helm/yas
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  ignoreDifferences:
    # Bỏ qua container istio-proxy được inject tự động
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - '.spec.template.spec.containers[] | select(.name == "istio-proxy")'
    # Bỏ qua các config volumes của Istio
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - '.spec.template.spec.volumes[] | select(.name == "istio-envoy" or .name == "istio-certs" or .name == "istio-token")'
    # Bỏ qua các annotations do Istio tự động gắn vào Pod template
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - '.spec.template.metadata.annotations'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
