{{- range $serviceName, $serviceConfig := .Values }}
{{- if typeIs "map[string]interface {}" $serviceConfig }}
{{- if hasKey $serviceConfig "enabled" }}
{{- if eq $serviceConfig.enabled true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      {{- if $serviceConfig.isBackend }}
      volumes:
        - name: yas-configuration
          configMap:
            name: yas-configuration-configmap
      {{- end }}
      containers:
        - name: {{ $serviceName }}
          image: "{{ $serviceConfig.image.repository }}:{{ $serviceConfig.image.tag }}"
          imagePullPolicy: IfNotPresent
          {{- if $serviceConfig.service }}
          ports:
            - containerPort: {{ $serviceConfig.service.port }}
          {{- end }}
          {{- if $serviceConfig.isBackend }}
          volumeMounts:
            - mountPath: /opt/yas/config
              name: yas-configuration
          {{- end }}
          resources:
            {{- toYaml $serviceConfig.resources | nindent 12 }}
          {{- if or $serviceConfig.env $serviceConfig.secrets $serviceConfig.isBackend }}
          envFrom:
            {{- if $serviceConfig.isBackend }}
            - secretRef:
                name: yas-postgresql-credentials-secret
            {{- end }}
            {{- if $serviceConfig.env }}
            - configMapRef:
                name: {{ $serviceName }}-config
            {{- end }}
            {{- if $serviceConfig.secrets }}
            - secretRef:
                name: {{ $serviceName }}-secret
            {{- end }}
          {{- end }}
          {{- if $serviceConfig.isBackend }}
          env:
            - name: LOGGING_CONFIG
              value: /opt/yas/config/logback.xml
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql.postgres:5432/{{ $serviceName }}
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: /opt/yas/config/application.yaml
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
