apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: yas-instrumentation
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: yas-instrumentation
spec:
  exporter:
    endpoint: http://opentelemetry-collector.observability:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
