{{- range $serviceName, $serviceConfig := .Values }}
{{- if typeIs "map[string]interface {}" $serviceConfig }}
{{- if hasKey $serviceConfig "enabled" }}
{{- if eq $serviceConfig.enabled true }}
{{- if $serviceConfig.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $serviceName }}
type: Opaque
data:
  {{- range $key, $val := $serviceConfig.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
