{{- range $serviceName, $serviceConfig := .Values }}
{{- if typeIs "map[string]interface {}" $serviceConfig }}
{{- if hasKey $serviceConfig "enabled" }}
{{- if hasKey $serviceConfig "image" }}
{{- if eq $serviceConfig.enabled true }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}