{{- range $serviceName, $serviceConfig := .Values }}
{{- if typeIs "map[string]interface {}" $serviceConfig }}
{{- if hasKey $serviceConfig "enabled" }}
{{- if eq $serviceConfig.enabled true }}
{{- if $serviceConfig.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $serviceName }}
spec:
  type: {{ $serviceConfig.service.type | default "NodePort" }}
  selector:
    app: {{ $serviceName }}
  ports:
    - name: http
      protocol: TCP
      port: {{ $serviceConfig.service.port }}
      targetPort: {{ $serviceConfig.service.port }}
      {{- if $serviceConfig.service.nodePort }}
      nodePort: {{ $serviceConfig.service.nodePort }}
      {{- end }}
    {{- if $serviceConfig.isBackend }}
    - name: metrics
      protocol: TCP
      port: 8090
      targetPort: 8090
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
