global:
  environment: dev
  domain: yas.dev.local.com
  identityDomain: identity.yas.dev.local.com
  keycloakInternalIP: ""
  redisHost: redis-master

backend:
  replicaCount: 1
  databaseConnectionUrl: jdbc:postgresql://postgresql:5432
  serviceMonitor:
    enabled: false
  image:
    pullPolicy: Always
  service:
    type: ClusterIP

ui:
  replicaCount: 1
  image:
    pullPolicy: Always
  service:
    type: ClusterIP

credentials:
  postgresql:
    username: yasadminuser
    password: admin
  elasticsearch:
    username: yas
    password: LarUmB3A49NTg9YmgW4=
  redis:
    password: redis
  openai:
    apiKey: update-me

redis:
  architecture: standalone
  auth:
    enabled: true
    password: redis

keycloak:
  hostname: identity.yas.dev.local.com
  backofficeRedirectUrl: http://backoffice.yas.dev.local.com
  storefrontRedirectUrl: http://storefront.yas.dev.local.com

kafka:
  kafka:
    replicas: 1
  zookeeper:
    replicas: 1
    storeSize: 5Gi

elasticsearch:
  replicas: 1

kibana:
  ingress:
    className: nginx
    hostname: kibana.yas.dev.local.com
